-- Real org data import: titles

insert into public.titles (name, meal_cost) values
  ('Admin Specialist', 75),
  ('Assistant Merchandising Audit', 120),
  ('Associate Product manager', 150),
  ('Business Analyst', 75),
  ('Business Intelligence Specialist', 75),
  ('Business Unit Director', 200),
  ('Business Unit manager', 200),
  ('CEO', 0),
  ('Channel Development Manager', 150),
  ('Chief Strategy Officer & HR Director', 300),
  ('Collection KAM', 75),
  ('Collection KAM Tender', 120),
  ('Collection Manager', 150),
  ('Collection Specialist', 120),
  ('Collection Supervisor', 100),
  ('Collection Tender Mngr.', 120),
  ('COMEX Director', 300),
  ('Commercial Manager', 150),
  ('Commex', 120),
  ('Compliance Officer', 180),
  ('Corporate business development manager', 150),
  ('Corporate COE & International Markets Manager', 150),
  ('CORPORATE DISTRIBUTION Collection Manager', 150),
  ('Corporate Field Trainer', 150),
  ('Corporate HR Director', 300),
  ('Corporate HR Specialist', 120),
  ('Corporate HR  Lead', 120),
  ('Corporate Medical Director', 300),
  ('Corporate Medical Lead', 150),
  ('CORPORATE Operations Lead', 100),
  ('CORPORATE Operations Manager', 150),
  ('Corporate Portfolio and Licensing Manager', 150),
  ('Corporate Portfolio Director', 300),
  ('Corporate Portfolio Lead', 150),
  ('Corporate Sales Forces Effectiveness Manager', 200),
  ('CORPORATE STORE Collection Manager', 150),
  ('Corporate TA & Communication Manager', 150),
  ('Corporate Tender Director', 300),
  ('Director Commercial Strategy & Explorer', 300),
  ('Dist. Sales Specialist', 75),
  ('Dist. Sales Supervisor', 100),
  ('Distributor Sales Manager', 150),
  ('Distributors Manager', 150),
  ('Distributors Senior Specialist', 75),
  ('Distributors Specialist', 75),
  ('District Manager', 150),
  ('Events corporate coordinator', 75),
  ('Explorer lead', 100),
  ('Export Manager', 0),
  ('Field Trainer', 150),
  ('GM', 300),
  ('Group product Manager', 150),
  ('HR Admin', 75),
  ('HR Associate', 120),
  ('HR Business Partner', 150),
  ('HR Manager', 150),
  ('HR Operation', 75),
  ('IT Lead', 120),
  ('KAM Tender', 120),
  ('Key Account Manager', 150),
  ('Key Account Specialist', 120),
  ('Launch Operations Lead', 120),
  ('Market Access', 120),
  ('Market Access Manager', 150),
  ('Marketing  Director', 200),
  ('Marketing manager', 150),
  ('Marketing manager', 150),
  ('Medical Advisor', 150),
  ('Medical Director', 300),
  ('Medical Rep', 120),
  ('Medical Sciense Liason', 150),
  ('MKT Access & BI Head', 200),
  ('National KAM', 180),
  ('National Sales Manager', 180),
  ('Office manager', 75),
  ('Oncology KAM, Tender and Distribution Lead', 150),
  ('Operation Manager', 150),
  ('Operation Senior Specialist', 100),
  ('Operation Specialist', 75),
  ('Operations Senior Specialist', 75),
  ('Operations Specialist', 120),
  ('PHI Specialist', 120),
  ('Portfolio Analyst', 120),
  ('Product manager', 150),
  ('Product manager Yemen', 150),
  ('Regional KAM', 180),
  ('Regional Sales Manager', 180),
  ('RSM Tender', 150),
  ('Sales & Distribution Director', 200),
  ('Sales Director', 200),
  ('Sales Forces Effectiveness Manager', 150),
  ('Sales Manager', 150),
  ('Senior Admin Specialist', 75),
  ('Senior Field trainer', 150),
  ('Store Sales Manager', 150),
  ('Store Sales Specialist', 75),
  ('Store Sales Supervisor', 100),
  ('Stores Manager', 150),
  ('Stores Senior Specialist', 75),
  ('Stores Specialist', 75),
  ('Sub-agents Sales Manager', 150),
  ('Sub-agents Sales Specialist', 75),
  ('Supply & Distributors', 75),
  ('Trade activation manager', 150),
  ('Trade Marketing Manager', 150),
  ('Training Cordinator', 75),
  ('Training Manager', 150),
  ('UPA MANAGER', 150);
